platform :ios, '11.0'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'meshApllication' do
 # BLE mesh
  pod 'SwiftLint'
  pod 'nRFMeshProvision'

  # pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'
  # pod 'react-native-ble-plx-swift', :path => '../node_modules/react-native-ble-plx'
end